resources:
  - name: simple-mock-app
    type: git
    icon: github
    source:
      uri: https://github.com/veronikaEve/simple-mock-app
      branch: master

  - name: img-node
    type: registry-image
    source:
      repository: node
      tag: 16.14.0-stretch # node version

jobs:
  - name: unit-test
    public: true
    plan:
      - get: img-node
      - get: simple-mock-app
        trigger: true # triggers job when the simple-mock-app resource changes, i.e. there is a new commit pushed to master
      - task: install
        image: img-node
        config:
          inputs:
            - name: simple-mock-app # gets the simple-mock-app resource and places it in a folder called simple-mock-app
          outputs:
            - name: app # after doing the install -> it puts the new folder (with all the newly install stuff) into a folder called app | this persists and is used by the test task
              path: simple-mock-app # app contains simple-mock-app
          platform: linux
          run: # runs `yarn install` in the simple-mock-app directory
            path: yarn
            args: ["install"]
            dir: simple-mock-app
      - task: test
        image: img-node
        config:
          inputs: # this input is what the install task outputted
            - name: app
              path: simple-mock-app
          platform: linux
          run: # runs `yarn run jest` in the simple-mock-app directory
            path: yarn
            args: ["run", "jest"]
            dir: simple-mock-app
  - name: deploy-release
    public: true
    plan:
      - in_parallel:
          - get: img-node
          - get: simple-mock-app
            passed: [unit-test]
      - task: deploy-heroku
        params:
          HEROKU_EMAIL: ((heroku_email))
          HEROKU_TOKEN: ((heroku_token))
        image: img-node
        config:
          platform: linux
          inputs:
            - name: simple-mock-app
          run:
            path: sh
            dir: simple-mock-app
            args:
              - -exc
              - |
                cat > /root/.netrc <<EOF
                machine git.heroku.com
                  login $HEROKU_EMAIL
                  password $HEROKU_TOKEN
                EOF
                git push https://git.heroku.com/simple-mock-app.git master:refs/heads/master
  # ^ TODO: change to be able to push to heroku git master from a different branch
  #  - https://devcenter.heroku.com/articles/git#deploy-from-a-branch-besides-main
  #  issues encountered while trying to implement that feature:
  #  - https://devcenter.heroku.com/articles/duplicate-build-version#diagnosing-deploys-from-a-different-branch
  - name: rollback-release
    public: true
    plan:
      - in_parallel:
          - get: img-node
          - get: simple-mock-app
      - task: deploy-heroku
        params:
          HEROKU_EMAIL: ((heroku_email))
          HEROKU_TOKEN: ((heroku_token))
        image: img-node
        config:
          platform: linux
          inputs:
            - name: simple-mock-app
          run:
            path: sh
            dir: simple-mock-app
            args:
              - -exc
              - |
                curl https://cli-assets.heroku.com/install.sh | sh
                cat > /root/.netrc <<EOF
                machine api.heroku.com
                  login $HEROKU_EMAIL
                  password $HEROKU_TOKEN
                EOF
                heroku rollback -a simple-mock-app

# Login Docs for writing to .netrc file: https://devcenter.heroku.com/articles/authentication#usage-examples
